### ISSUE TITLE
Defining primary client of a project

### ISSUE THREAD

**Issue by fredrikaverpil** [eoyilmaz/stalker#37]
In Stalker `0.2.15.1`:

> New: Project to Client relation is now a many-to-many relation, thus it is possible to set multiple Clients for each project with each client having their own roles in a specific project.

In our production management GUI, we show projects prefixed with the client company name. I'd like to keep this and I'm thinking I can just add a `Client.id` to `Project.generic_text` to indicate which Client is the "primary" one, now when there's not a single client associated with a project any longer.

So, I was just wondering if you already had something like this in mind ([docs](https://pythonhosted.org/stalker/) doesn't seem updated) and if there was already a better attribute in place already for this use case?

**Comment by eoyilmaz** [comment]
Ohh yes I've not updated the docs yet sorry.

Use the ``ProjectClient.role`` attribute to define the primary client. So each client can have different **roles** per project basis.

So instead of assigning the client to the ``Project.clients`` list you can assign one ``Client`` to a ``Project`` by creating a ``ProjectClient`` instance (which is an association proxy, and created automatically when you assign a client to ``Project.clients`` list):

```Python
p1 = Project(...)
c1 = Client(...)
role = Role(name='Primary Client')
pc1 = ProjectClient(project=p1, client=c1, role=role)
```

or you can update the role if you have already assigned the ``Client`` to the ``Project`` by:
```Python
role = Role(name='Primary Client')
pc1 = ProjectClient.query.filter(ProjectClient.project==p1).filter(ProjectClient.client==client).first()
pc1.role = role
```

**Comment by fredrikaverpil** [comment]
Excellent, thank you! 😃
