### ISSUE TITLE
is Stalker Pyramid dead ?

### ISSUE THREAD

**Issue by predat** [eoyilmaz/stalker#41]
or there a replacement ?

**Comment by eoyilmaz** [comment]
No it is not dead :) we are actively developing it.

But it is not opensource because of its dependencies to non-opensource code.

We were planing to release it in February 2017 but I'm very suspected that it will happen at that time. But it will in near future.

We've already coded a good chunk of it from scratch and will keep develeoping it, because we are actively using it in our studio for our projects.

Sorry for the inconveniences.
